async (page) => {
  const revision = page.getByRole('region', { name: '路线调整', exact: true });
  const route = page.getByRole('article', { name: '路线详情', exact: true });
  const base = page.url().split('/').slice(0, 3).join('/');
  const id = page.url().split('#roadmap-')[1];
  const read = async () => (await page.request.get(`${base}/api/roadmaps/${id}`)).json();
  const todos = async () => (await page.request.get(`${base}/api/todos`)).json();
  const openDraft = async () => {
    if (!await revision.getByLabel('路线标题', { exact: true }).isVisible())
      await revision.getByText('手动编辑调整草稿（无需模型）', { exact: true }).click();
  };
  const preview = async () => {
    await revision.getByRole('button', { name: '预览手动调整', exact: true }).click();
    await revision.getByRole('heading', { name: '待确认调整', exact: true }).waitFor();
  };
  const confirm = () => revision.getByRole('button', { name: '确认此调整方案', exact: true }).click();
  const before = await read();
  await openDraft();
  await revision.getByRole('group', { name: '草稿节点 1', exact: true }).getByLabel('练习', { exact: true }).fill('只运行一次 SET 和 GET，并记录输出');
  await preview();
  if (JSON.stringify((await read()).nodes) !== JSON.stringify(before.nodes)) throw new Error('Preview changed nodes');
  await page.reload();
  await confirm();
  await route.getByRole('region', { name: '节点 1', exact: true }).getByText('练习：只运行一次 SET 和 GET，并记录输出', { exact: true }).waitFor();
  if ((await todos()).length) throw new Error('Candidate revision created todo');
  await page.getByRole('checkbox', { name: '选择节点 1：练习 Redis 字符串读写', exact: true }).check();
  await page.getByRole('button', { name: '确认加入所选 1 项', exact: true }).click();
  await page.getByRole('heading', { name: '已保存的待办 1', exact: true }).waitFor();
  await openDraft();
  const first = revision.getByRole('group', { name: '草稿节点 1', exact: true });
  await first.getByLabel('候选待办标题', { exact: true }).fill('完成简化的 Redis 练习');
  await first.getByLabel('节点日期', { exact: true }).fill('2026-10-05');
  await preview();
  const beforeRefusal = await read();
  const beforeTodos = await todos();
  await revision.getByRole('button', { name: '暂不同步，保留整份方案', exact: true }).click();
  await page.getByText(/尚未明确同意方案中全部待办同步范围/).first().waitFor();
  if (JSON.stringify((await read()).nodes) !== JSON.stringify(beforeRefusal.nodes) || JSON.stringify(await todos()) !== JSON.stringify(beforeTodos)) throw new Error('Refusal mutated state');
  await revision.getByRole('checkbox', { name: '同意同步待办及关联学习内容：练习 Redis 字符串读写', exact: true }).check();
  await confirm();
  await route.getByRole('region', { name: '节点 1', exact: true }).getByText('当前节点安排：2026-10-05', { exact: true }).waitFor();
  if ((await todos())[0].title !== '完成简化的 Redis 练习') throw new Error('Todo title not synchronized');
  await openDraft();
  await first.getByLabel('练习', { exact: true }).fill('这份旧方案不应生效');
  await preview();
  const second = await page.context().newPage();
  await second.goto(page.url());
  await second.getByRole('button', { name: '＋ 新会话', exact: true }).click();
  await second.getByRole('region', { name: '节点 1', exact: true }).getByRole('button', { name: '标记已掌握（同步完成待办）', exact: true }).click();
  await second.getByText('学习进度：已完成 1 / 2， 剩余 1 个节点', { exact: true }).waitFor();
  const fact = (await read()).nodes[0].completion;
  await revision.getByRole('checkbox', { name: '同意同步待办及关联学习内容：完成简化的 Redis 练习', exact: true }).check();
  await confirm();
  await revision.getByRole('heading', { name: '调整方案冲突，请重新生成', exact: true }).waitFor();
  await second.close();
  await openDraft();
  const completed = revision.getByRole('group', { name: '草稿节点 1（已完成，内容受保护）', exact: true });
  if (await completed.getByLabel('练习', { exact: true }).isEnabled()) throw new Error('Completed content editable');
  await completed.getByRole('button', { name: '移出当前顺序（保留历史）', exact: true }).click();
  await preview();
  await confirm();
  await route.getByRole('region', { name: '历史节点 理解字符串读写', exact: true }).waitFor();
  await page.reload();
  await route.getByRole('region', { name: '历史节点 理解字符串读写', exact: true }).waitFor();
  const final = await read();
  if (JSON.stringify(final.history_nodes[0].completion) !== JSON.stringify(fact)) throw new Error('Lost completion history');
  if ((await todos()).length !== 1 || (await todos())[0].status !== 'completed') throw new Error('Lost completed todo');
  await route.getByRole('region', { name: '历史节点 理解字符串读写', exact: true }).screenshot({ path: 'output/playwright/issue24-history.png' });
  console.log('PASS: unjoined edit, preview/reload, refusal, explicit sync, dates, cross-session conflict, completed protection, archived history');
}
