async (page) => {
  const base = page.url().split('/').slice(0, 3).join('/');
  const route = page.getByRole('article', { name: '路线详情', exact: true });
  const schedule = page.getByRole('region', { name: '路线排期', exact: true });
  await page.getByRole('checkbox', { name: '选择节点 1：练习 Redis 字符串读写', exact: true }).check();
  await page.getByRole('button', { name: '确认加入所选 1 项', exact: true }).click();
  await page.getByRole('heading', { name: '已保存的待办 1', exact: true }).waitFor();
  await schedule.getByLabel('起始日期', { exact: true }).fill('2026-10-01');
  await schedule.getByLabel('每个学习日可用分钟', { exact: true }).fill('30');
  await schedule.getByRole('button', { name: '预览排期', exact: true }).click();
  await schedule.getByRole('heading', { name: '待确认排期', exact: true }).waitFor();
  const routes = await (await page.request.get(`${base}/api/roadmaps`)).json();
  const read = async () => (await page.request.get(`${base}/api/roadmaps/${routes[0].id}`)).json();
  let current = await read();
  if (current.nodes.some(n => n.scheduled_date !== null)) throw new Error('Preview changed dates');
  await page.reload();
  await schedule.getByRole('button', { name: '确认此排期方案', exact: true }).click();
  await route.getByRole('region', { name: '节点 1', exact: true }).getByText('当前节点安排：2026-10-01', { exact: true }).waitFor();
  current = await read();
  if (current.nodes[0].todo.scheduled_date !== '2026-10-01') throw new Error('Linked todo not synchronized');
  if ((await (await page.request.get(`${base}/api/todos`)).json()).length !== 1) throw new Error('Schedule created todos');
  await page.getByRole('checkbox', { name: '选择节点 2：验证 Redis 缓存过期', exact: true }).check();
  await page.getByRole('button', { name: '确认加入所选 1 项', exact: true }).click();
  await page.getByRole('heading', { name: '已保存的待办 2', exact: true }).waitFor();
  current = await read();
  if (current.nodes[1].todo.scheduled_date !== '2026-10-02') throw new Error('Future acceptance lost planned date');
  await schedule.getByLabel('起始日期', { exact: true }).fill('2026-10-05');
  await schedule.getByLabel('每个学习日可用分钟', { exact: true }).fill('30');
  await schedule.getByRole('button', { name: '预览排期', exact: true }).click();
  await schedule.getByRole('heading', { name: '待确认排期', exact: true }).waitFor();
  const second = await page.context().newPage();
  await second.goto(page.url());
  await second.getByRole('button', { name: '＋ 新会话', exact: true }).click();
  await second.getByRole('region', { name: '节点 3', exact: true }).getByRole('button', { name: '标记已掌握（不创建待办）', exact: true }).click();
  await second.getByText('学习进度：已完成 1 / 3， 剩余 2 个节点', { exact: true }).waitFor();
  await schedule.getByRole('button', { name: '确认此排期方案', exact: true }).click();
  await schedule.getByRole('heading', { name: '方案已过期，请重新预览', exact: true }).waitFor();
  await second.close();
  await schedule.getByRole('button', { name: '预览清空日期', exact: true }).click();
  await schedule.getByRole('heading', { name: '待确认排期', exact: true }).waitFor();
  await schedule.getByRole('button', { name: '确认此排期方案', exact: true }).click();
  await route.getByRole('region', { name: '节点 1', exact: true }).getByText('当前节点安排：未安排', { exact: true }).waitFor();
  await page.reload();
  await route.getByText('学习进度：已完成 1 / 3， 剩余 2 个节点', { exact: true }).waitFor();
  current = await read();
  if (current.nodes[2].scheduled_date !== '2026-10-03' || current.nodes[2].status !== 'completed') throw new Error('Completed node changed');
  if (current.nodes.slice(0, 2).some(n => n.todo.scheduled_date !== null)) throw new Error('Dates not cleared');
  await schedule.screenshot({ path: 'output/playwright/issue23-schedule.png' });
  console.log('PASS: preview unchanged, reload restore, confirmation sync, future acceptance, cross-session stale rejection, clear dates, completed protection');
}
