async (page) => {
  const base = page.url().split('/').slice(0, 3).join('/');
  const id = page.url().split('#roadmap-')[1];
  const read = async () => (await page.request.get(`${base}/api/roadmaps/${id}`)).json();
  const todos = async () => (await page.request.get(`${base}/api/todos`)).json();
  const route = page.getByRole('article', { name: '路线详情', exact: true });
  const schedule = page.getByRole('region', { name: '路线排期', exact: true });
  const revision = page.getByRole('region', { name: '路线调整', exact: true });
  if ((await todos()).length) throw new Error('Generation created todos');
  await page.getByRole('checkbox', { name: '选择节点 1：练习 Redis 字符串读写', exact: true }).check();
  await page.getByRole('button', { name: '确认加入所选 1 项', exact: true }).click();
  await page.getByRole('heading', { name: '已保存的待办 1', exact: true }).waitFor();
  if ((await todos())[0].scheduled_date !== null) throw new Error('Unexpected default date');
  await schedule.getByLabel('起始日期', { exact: true }).fill('2026-10-01');
  await schedule.getByLabel('每个学习日可用分钟', { exact: true }).fill('30');
  await schedule.getByRole('button', { name: '预览排期', exact: true }).click();
  await schedule.getByRole('heading', { name: '待确认排期', exact: true }).waitFor();
  if ((await todos())[0].scheduled_date !== null) throw new Error('Preview changed date');
  await page.reload();
  await schedule.getByRole('button', { name: '确认此排期方案', exact: true }).click();
  await route.getByRole('region', { name: '节点 1', exact: true }).getByText('当前节点安排：2026-10-01', { exact: true }).waitFor();
  if ((await todos()).length !== 1) throw new Error('Schedule created todos');
  await page.getByRole('checkbox', { name: '选择节点 2：验证 Redis 缓存过期', exact: true }).check();
  await page.getByRole('button', { name: '确认加入所选 1 项', exact: true }).click();
  await page.getByRole('heading', { name: '已保存的待办 2', exact: true }).waitFor();
  await route.getByRole('region', { name: '节点 1', exact: true }).getByRole('button', { name: '标记已掌握（同步完成待办）', exact: true }).click();
  await route.getByText('学习进度：已完成 1 / 2， 剩余 1 个节点', { exact: true }).waitFor();
  const fact = (await read()).nodes[0].completion;
  await revision.getByText('手动编辑调整草稿（无需模型）', { exact: true }).click();
  const second = revision.getByRole('group', { name: '草稿节点 2', exact: true });
  await second.getByLabel('候选待办标题', { exact: true }).fill('观察缓存倒计时和过期结果');
  await second.getByLabel('练习', { exact: true }).fill('设置 EX 10，立即查看 TTL，等待后再 GET');
  await revision.getByRole('button', { name: '预览手动调整', exact: true }).click();
  await revision.getByRole('heading', { name: '待确认调整', exact: true }).waitFor();
  const before = await read();
  await revision.getByRole('button', { name: '暂不同步，保留整份方案', exact: true }).click();
  await page.getByText(/尚未明确同意方案中全部待办同步范围/).first().waitFor();
  if (JSON.stringify((await read()).nodes) !== JSON.stringify(before.nodes)) throw new Error('Refusal changed nodes');
  await revision.getByRole('checkbox', { name: '同意同步待办及关联学习内容：验证 Redis 缓存过期', exact: true }).check();
  await revision.getByRole('button', { name: '确认此调整方案', exact: true }).click();
  await route.getByRole('region', { name: '节点 2', exact: true }).getByText('练习：设置 EX 10，立即查看 TTL，等待后再 GET', { exact: true }).waitFor();
  await page.getByRole('button', { name: '＋ 新会话', exact: true }).click();
  await page.reload();
  await route.getByText('学习进度：已完成 1 / 2， 剩余 1 个节点', { exact: true }).waitFor();
  const final = await read();
  if (JSON.stringify(final.nodes[0].completion) !== JSON.stringify(fact)) throw new Error('Completion lost');
  if (final.nodes[1].todo.title !== '观察缓存倒计时和过期结果' || final.nodes[1].todo.scheduled_date !== '2026-10-02') throw new Error('Revision lost linked schedule');
  if ((await todos()).length !== 2) throw new Error('Duplicate or missing todo');
  await route.screenshot({ path: 'output/playwright/issue18-journey.png' });
  console.log('PASS: selection, date preview/confirmation, later acceptance, completion, revision refusal/sync, refresh and new session');
}
